### ISSUE TITLE
Shoutbox is broken

### ISSUE THREAD

**Issue by Phhere** [webSPELL/webSPELL-4.2.3#115] opened 2015-01-06 18:39 UTC

**Comment by derchrisuk** [comment] 2015-01-06 19:17
Cannot reproduce.
Both posting as guest/user, no error.

**Comment by derchrisuk** [comment] 2015-01-08 13:25
Closing issue.
Several entries into Shoutbox on dev did not show any errors.

**Closed by derchrisuk** 2015-01-08 13:25 UTC
Labels: skill:easy, type:bug
